name: NPM Worker
on:
  push:
    paths:
      - .github/npmworker.config.yaml
jobs:
  npm:
    runs-on: ubuntu-latest
    name: NPM Worker
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: NPM Worker
        uses: mudlabs/npm-worker@v1.3.0
        with:
          config: .github/npmworker.config.yaml
      - name: Commit
        uses: EndBug/add-and-commit@v5.1.0
